### ISSUE TITLE
The instructions on Windows don't work

### ISSUE THREAD

**Issue by stuwags** [commaai/eon-neos#14]
I get the following error when running .\flash.ps1

Expand-Archive : The path 'platform-tools-latest-windows.zip' either does not exist or is not a valid file system path.
At C:\Users\stu-win\eon-neos\flash.ps1:12 char:5
+     Expand-Archive -Path "platform-tools-latest-windows.zip" -Destina ...
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (platform-tools-latest-windows.zip:String) [Expand-Archive], InvalidOpe
   rationException
    + FullyQualifiedErrorId : ArchiveCmdletPathNotFound,Expand-Archive

**Comment by pd0wm** [comment]
Should be fixed by https://github.com/commaai/eon-neos/commit/69556e38496a31dd781b23925a49b252bf8de170
