### ISSUE TITLE
Issue running fastboot flash boot files\boot.img

### ISSUE THREAD

**Issue by sanchezluciano** [commaai/eon-neos#15]
I receive the following error when I am running the installer; specifically the "fastboot flash boot files\boot.img" command:
`fastboot: error: Couldn't parse partition size '0x'.`

After that when the "fastboot flash system files\system.img" command runs, it completes fine.

I am running this on a Windows 10 computer. All the other steps seem to work fine. Any help is appreciated. 

Thanks!

**Comment by sanchezluciano** [comment]
For anyone experiencing a similar issue I was able to resolve that error by running the commands in the flash.ps1 file manually.

To resolve the specific error I used the command:
'fastboot boot files/boot.img'
to install the boot image.

**Comment by sanchezluciano** [comment]
Just kidding guys. That only allowed the boot image to run but not be flashed. So it allows the phone to boot but if you restart the phone it will not boot because it doesn't have the image flashed. Still needing help if anyone can. Thanks!

**Comment by adeebshihadeh** [comment]
Closed by mistake. Have you tried a different version of fastboot?

**Comment by sanchezluciano** [comment]
No worries. I have not. Is there one that is recommended?

**Comment by sanchezluciano** [comment]
I just tried it on Minimal_ADB_Fastboot_v1.3 and it worked. Thanks for that @adeebshihadeh :)

**Comment by crdnl** [comment]
I was needing to do this as well.

My installed version is
> fastboot version 30.0.1-6435776
> Installed as /usr/local/bin/fastboot

The version downloaded is
> fastboot version 30.0.4-6686687
> Installed as /Users/<snip>/Documents/projects/eon-neos/platform-tools/./fastboot

So something broke between the two versions......

**Comment by pd0wm** [comment]
Fixed with: https://github.com/commaai/eon-neos/commit/69556e38496a31dd781b23925a49b252bf8de170

**Comment by Smitherten** [comment]
i thank this thread with all my life, i was rooting my phone with magick, and "fastboot flash boot magisk_patched.img" did not work, so i thank this thread alot.
