### ISSUE TITLE
VW community version - error - failed to download recovery

### ISSUE THREAD

**Issue by DEEgao888** [commaai/eon-neos#19]
I might need to downgrade to NEOS 14 to use the VW community openpilot. 

Does anyone know how to downgrade it?

Restoring on Linux/OS X
Connect your comma two (via a USB-C to USB-A cable) or EON (via a USB-mini-B to USB-A cable) to your computer
Open a terminal
Clone this repo git clone https://github.com/commaai/eon-neos.git, then cd into the cloned repo cd eon-neos
Run ./download.py
Put your device into fastboot mode by turning off your device, then holding volume down + power (comma two, EON Gold), or volume up + power (EON).
Run ./flash.sh DO NOT DISCONNECT THE DEVICE!

**Comment by VirtuallyChris** [comment]
The old version was removed. You can run this command to go back to openpilot 0.7.9 and get the old NEOS

`cd /data && rm -rf openpilot && git clone -b v0.7.9 https://github.com/commaai/openpilot && cd openpilot/installer/updater && rm update.json && wget https://cdn.discordapp.com/attachments/538741329799413760/774123747257876480/update.json && reboot`
