### ISSUE TITLE
OG EON has 2 small LED's on all of the time.

### ISSUE THREAD

**Issue by icmma** [commaai/eon-neos#2]
I haven't updated the NEOS until today because of tri-state issue.  I saw @chase shared picture of his EON while back where 2 LED's were lid up all of the time  i thought it was just his EON but turns out all of the EON's have them confirmed by 10 users which might possibly cause battery issue with EON? Sharing picture from chase since more visible.
![image0](https://user-images.githubusercontent.com/43789411/52158758-5f529e80-2650-11e9-978d-f77e5b57f20b.jpg)

**Comment by SippieCup** [comment]
Those are the captive touch button indicators. Might help in diagnosis

**Comment by icmma** [comment]
you are right @SippieCup 
https://forums.oneplus.com/threads/led-indicator-in-capacitive-touch-buttons.503637/

**Comment by icmma** [comment]
https://forums.androidcentral.com/samsung-galaxy-s6/514293-how-turn-off-adjust-capacitive-hardware-button-lights-s6-s6e.html

**Comment by martinl** [comment]
Hi

`settings put system button_key_light 0` does not disable button leds on 3T with latest NEOSv8
I believe the missing interface is `/sys/class/leds/button-backlight/brightness`. Can you please add it?

source: https://forums.oneplus.com/threads/keep-button-backlights-on-root.508092/

Martin

**Comment by neon-dev** [comment]
According to https://forums.oneplus.com/threads/keep-button-backlights-on-root.508092/ there should be an entry called `/sys/class/leds/button-backlight` which doesn't. Maybe that's already the reason?
Don't know enough about the matter to provide further help. I just know that you can't simply create said folder, so we can't even test if `echo 0 > /sys/class/leds/button-backlight/brightness` would turn the LEDs off.

**Comment by vanillagorillaa** [comment]
Fixed, https://github.com/commaai/android_kernel_comma_msm8996/pull/4
