### ISSUE TITLE
EON (first version, not the 2nd version) no power

### ISSUE THREAD

**Issue by pedrojr123** [commaai/eon-neos#23]
I was parked waiting for my kids at the bus stop, everything was running perfectly on my Toyota Corolla2017, all of a sudden I see the screen go blue, then lost power. Tried restarting a few times and I could feel the vibration while holding the power button. Then I started to mess pressing the buttons (up and down) at the same time that I pressed the power.  Haven't gotten any kind of vibration since. I opened it up and try to charge it via its C port, no luck, no power at all.  Hoping I could get some advise.

**Comment by adeebshihadeh** [comment]
If your hardware is still under warranty, contact support@comma.ai. Otherwise, the community discord may be able to help you out.
