### ISSUE TITLE
need ignition emulation on panda jungle

### ISSUE THREAD

**Issue by ezhonghawke** [commaai/eon-neos#26]
I would like to make comma2 work without deploying it to a real vehicle. 
I have panda jungle that can connect the comma2. However, it doesn't have a switch to turn on the ignition like the debug board. It would be nice to have some software emulating ignition to engage comma2 with panda jungle.

**Comment by vanillagorillaa** [comment]
This really doesn't have anything to do with NEOS. With that being said, you can use the Panda Jungle Repo (https://github.com/commaai/panda_jungle), and this script to toggle ignition, https://github.com/commaai/panda_jungle/blob/master/tests/start.py
