### ISSUE TITLE
ERROR: Couldn't create a device interface iterator

### ISSUE THREAD

**Issue by eugesd** [commaai/eon-neos#28]
I upgraded to a new version of openpilot (v0.7.6.1 from custom fork of v0.6 with Prius Prime 2020 support before it was officially allowed) which then gave me a prompt saying I needed to update eon-neos. I tried updating from the phone directly but the update failed. I then found I should try to directly flash it. I tried following the directions given here, but now it no longer boots, and just goes into an infinite boot loop. This was working before trying to upgrade. I'm on macOS Catalina v10.15.7.

` $./flash.sh 
Password:
ERROR: Couldn't create a device interface iterator: (e00002bd)
                                                   FAILED (remote: 'unknown command')
fastboot: error: Command failed
ERROR: Couldn't create a device interface iterator: (e00002bd)
Sending 'recovery' (14853 KB)                      OKAY [  0.351s]
Writing 'recovery'                                 OKAY [  0.116s]
Finished. Total time: 0.526s
ERROR: Couldn't create a device interface iterator: (e00002bd)
Sending 'boot' (11677 KB)                          OKAY [  0.280s]
Writing 'boot'                                     OKAY [  0.098s]
Finished. Total time: 0.421s
ERROR: Couldn't create a device interface iterator: (e00002bd)
Invalid sparse file format at header magic
Sending sparse 'system' 1/7 (378630 KB)            OKAY [  9.491s]
Writing 'system'                                   OKAY [  4.453s]
Sending sparse 'system' 2/7 (419091 KB)            OKAY [ 10.170s]
Writing 'system'                                   OKAY [  4.298s]
Sending sparse 'system' 3/7 (417936 KB)            OKAY [ 10.325s]
Writing 'system'                                   OKAY [  4.310s]
Sending sparse 'system' 4/7 (424223 KB)            OKAY [ 10.453s]
Writing 'system'                                   OKAY [  5.061s]
Sending sparse 'system' 5/7 (424959 KB)            OKAY [ 10.872s]
Writing 'system'                                   OKAY [  6.130s]
Sending sparse 'system' 6/7 (410724 KB)            OKAY [  9.953s]
Writing 'system'                                   OKAY [ 43.766s]
Sending sparse 'system' 7/7 (15388 KB)             OKAY [  0.396s]
Writing 'system'                                   OKAY [  0.121s]
Finished. Total time: 136.736s
ERROR: Couldn't create a device interface iterator: (e00002bd)
******** Did you mean to fastboot format this ext4 partition?
Erasing 'userdata'                                 OKAY [ 12.937s]
Finished. Total time: 12.965s
ERROR: Couldn't create a device interface iterator: (e00002bd)
mke2fs 1.44.4 (18-Aug-2018)
Creating filesystem with 65536 4k blocks and 65536 inodes
Filesystem UUID: fa7d5c4a-9740-45ca-8f80-059edb772bd3
Superblock backups stored on blocks: 
	32768

Allocating group tables: done                            
Writing inode tables: done                            
Creating journal (4096 blocks): done
Writing superblocks and filesystem accounting information: done

Sending 'cache' (120 KB)                           OKAY [  0.040s]
Writing 'cache'                                    OKAY [  0.025s]
Finished. Total time: 0.171s
ERROR: Couldn't create a device interface iterator: (e00002bd)
Rebooting                                          OKAY [  0.000s]
Finished. Total time: 0.000s`

**Comment by vanillagorillaa** [comment]
Looks like this error is something to do with the version of android platform tools that you are running. I found this thread when google searching for your issue. https://android.stackexchange.com/questions/209725/fastboot-devices-command-doesnt-work-after-macos-high-sierra-10-14-4-upgrade

As far as the boot looping device issue goes. It sounds like you have a OnePlus 3T based EON which is no longer supported in NEOS16 (the version in this repo). You will need NEOS15 for your device and you can roll back to this commit to be able to download the proper version. https://github.com/commaai/eon-neos/commit/d7aa5d9440a6b9b287cad1858b219ac13374d422
