### ISSUE TITLE
what's the last version support for oneplus 3T mobile?

### ISSUE THREAD

**Issue by ATcn** [commaai/eon-neos#37]
oneplus 3T mobile = op3t

case:
try flash neos **15.1** into op3t mobile, result: flash ok! boot system **ok**
didn't find neos **16.1** rom zip uri
try flash neos **18** into op3t mobile, result: flash ok! boot system **fail!** fail(loop to fastboot mode) 

question:
what's the last version, that can run in op3t ?

**Comment by adeebshihadeh** [comment]
0.8.2 was the last supported version for the OnePlus 3T. You'll need to flash the matching NEOS version and clone openpilot 0.8.2 manually.

**Comment by ATcn** [comment]
> 0.8.2 was the last supported version for the OnePlus 3T. You'll need to flash the matching NEOS version and clone openpilot 0.8.2 manually.

get a info: op(0.7.10-0.82)	depend	neos 15.1
so neos 15.1 + op0.82 是这last version for op3t

thanks for your soon reply
