### ISSUE TITLE
Oneplus 3T keeps on fastboot interface after ran ./flash.sh

### ISSUE THREAD

**Issue by hi-hai** [commaai/eon-neos#39]
Restarted but phone doesn't load into NEOS but keeping on the fastboot mode. The bootloader version doesn't show, device unlocked.

fastboot devices can show the device.

**Comment by adeebshihadeh** [comment]
The latest NEOS isn't compatible with the OnePlus 3T.

**Comment by hi-hai** [comment]
What is the latest compatible version for OnePlus 3T?

**Comment by bdytx5** [comment]
What is the latest compatible version for OnePlus 3/T?
